Add "NO_INTERNET" description to INSTALL document for runtests.py failing error
If it fails with runtests.py when building on non interconnected hosts like this;
  ```
    File "../tests/runtests.py", line 79, in runtests
    raise Exception('Tests failed. Got "%s", expected "%s"' % (result, expected_result))
  Exception: Tests failed. Got "END-OF-SCRIPT", expected "isResolvable"
  ```
  Please set an environment variable NO_INTERNET. Then it won't require internet.
  ```
  $ export NO_INTERNET=1 && make -C src install-pymod
  ```